Update CODEOWNERS
camaraproject/SubscriptionStatus pull request #5
Opened 2024-09-29 08:21 UTC by chinaunicomyangfan

#### What type of PR is this?

Add one of the following kinds:

* subproject management

#### What this PR does / why we need it:

Update codeowners of SubscriptionStatus

2024-09-29 12:11 UTC, hdamker requested changes
Waiting with approval and merge until @Ryaaan308 has accepted the invitation (to get a valid CODEOWNERS file).

2024-09-30 14:57 UTC, hdamker commented
> @hdamker MAINTAINERS.md has been updated.

Thanks - LGTM. So we are ready as soon @Ryaaan308 has accepted and subscribed to [sp-kyc@lists.camaraproject.org](mailto:sp-kyc@lists.camaraproject.org)

2024-10-09 18:46 UTC, jgarciahospital commented
Checking if this was solved @hdamker @Ryaaan308

2024-10-09 20:53 UTC, hdamker commented
@jgarciahospital the invite of @ryaaan308 failed unfortunately, I have just retried the invitation. You can see if this is solved if the the CODEOWNERS here in the PR is valid.

@chinaunicomyangfan @DanXu-ChinaTelecom: can you reach out to @ryaaan308 and ask to login to GitHub and look for a message like this on top of the camaraproject?:

![Screenshot 2024-10-01 at 18 58 18](https://github.com/user-attachments/assets/31c55aec-512b-41e2-acfa-aef743dfff33)

2024-10-09 20:54 UTC, hdamker commented
@chinaunicomyangfan as an alternative you could delete @Ryaan308 from the CODEOWNERS file here and we are good to go.

2024-10-10 01:42 UTC, Ryaaan308 commented
@hdamker Sorry Herbert，last week I was on a vacation. Now I have already join in the project.
________________________________
发件人: Herbert Damker ***@***.***>
发送时间: 2024年10月10日 4:54
收件人: camaraproject/SubscriptionStatus ***@***.***>
抄送: ShuoRan ChinaUnicom ***@***.***>; Mention ***@***.***>
主题: Re: [camaraproject/SubscriptionStatus] Update CODEOWNERS and MATAINERS (PR #5)


@chinaunicomyangfan<https://github.com/chinaunicomyangfan> as an alternative you could delete @Ryaan308 from the CODEOWNERS file here and we are good to go.

―
Reply to this email directly, view it on GitHub<https://github.com/camaraproject/SubscriptionStatus/pull/5#issuecomment-2403411036>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVQM6EQB5WR3LYDCEVXWN2DZ2WJ2FAVCNFSM6AAAAABPBMSTUWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBTGQYTCMBTGY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-10 05:12 UTC, hdamker commented
> @hdamker Sorry Herbert，last week I was on a vacation. Now I have already join in the project

@Ryaaan308 Welcome! Would you mind to join the mailing lists https://lists.camaraproject.org/g/sp-kyc and https://lists.camaraproject.org/g/all as well?

2024-10-10 05:12 UTC, hdamker submitted a review, later dismissed

2024-10-27 05:23 UTC, ToshiWakayama-KDDI commented
Hi @Ryaaan308 , 

Welcome.  This is Toshi @ToshiWakayama-KDDI , KnowYourCustomer SP lead/primary contact.  I would like to make direct contact with you, so, could you send me an email?  You can find my email address at CAMARA Subprojects Wiki ( https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14552629/Sub+Projects ).  
Thanks.

2025-02-06 16:47 UTC, hdamker commented
I'm not sure why this approved wasn't merged ... @chinaunicomyangfan

2025-02-08 07:12 UTC, chinaunicomyangfan commented
> I'm not sure why this approved PR wasn't merged ... @chinaunicomyangfan

Sorry, due to internal work changes, this API has not been updated for a long time. We are preparing to restart this work, and @Ryaaan308  will no longer be involved in the work of this API. I will still be involved. At the same time, the colleagues involved in Huawei have also changed, from @philipxujin  to @ClownsAlbert and @ChuanyuChen. The Maintainer file has been updated.

2025-02-12 07:43 UTC, philipxujin approved these changes
OK

2025-02-12 10:55 UTC, hdamker commented
@chinaunicomyangfan @philipxujin thanks for the recent updates. I have invited @ClownsAlbert and @ChuanyuChen into the CAMARA organization, so that they can take the roles as proposed. They need to accept the invitation.

As the Maintainers of SubscriptionStatus will get also Maintainers of the parent Sub Project "Know Your Customer", I would like to ask @camaraproject/know-your-customer_maintainers to review and approve the proposed Maintainers, especially @ToshiWakayama-KDDI on behalf of the Sub Project.

2025-02-12 11:00 UTC, hdamker commented
P.S.: Removed [Ryaaan308](https://github.com/Ryaaan308) from the CAMARA organization.

2025-03-07 06:11 UTC, hdamker commented
Looks technically all good here, but I need 
a) an approval from @camaraproject/know-your-customer_maintainers (as these changes also the Sub Project Maintainers)
b) an approval from another @camaraproject/admins

2025-03-11 04:49 UTC, ToshiWakayama-KDDI approved these changes

2025-03-11 04:54 UTC, ToshiWakayama-KDDI commented
Hi @chinaunicomyangfan ,

Could you advise me of your email address, please?  You can find mine as KnowYourCustomer SP primary contact, e.g. in this page : https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14562054/KnowYourCustomer.

Many thanks,
Toshi

2025-03-11 07:31 UTC, hdamker approved these changes

2025-03-11 07:32 UTC, hdamker commented
GitHub teams and codeowners mailing list updated, all set here.

2025-03-11 07:32 UTC, merged

2025-03-11 07:41 UTC, chinaunicomyangfan commented
> Hi @chinaunicomyangfan ,
> 
> Could you advise me of your email address, please? You can find mine as KnowYourCustomer SP primary contact, e.g. in this page : https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14562054/KnowYourCustomer.
> 
> Many thanks, Toshi

Hi,@ToshiWakayama-KDDI ,thank you for the reminder. Sorry, we were having internal discussions regarding this API before. Fortunately, we have the discussion results and are ready to start the API development work next week. My email is **yangf94@chinaunicom.cn** If you have any questions, please feel free to contact me for discussion.